#!/usr/bin/env bash
# Registers the GoFish native messaging host with Chrome, Brave and Chromium.
# Chrome launches native hosts with a minimal PATH, so absolute paths to node
# and orca are baked into the generated wrapper rather than resolved at runtime.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_NAME="com.gofish.orca"
EXTENSION_ID="ecfigcjkbachiilipbonfikgmmadbcdd"

NODE_BIN="${NODE_BIN:-$(command -v node || true)}"
if [ -z "$NODE_BIN" ]; then
	echo "node not found. Install Node, or run: NODE_BIN=/path/to/node $0" >&2
	exit 1
fi

ORCA_BIN="${ORCA_BIN:-$(command -v orca || true)}"
if [ -z "$ORCA_BIN" ] && [ -x "$HOME/.local/bin/orca" ]; then
	ORCA_BIN="$HOME/.local/bin/orca"
fi
if [ -z "$ORCA_BIN" ]; then
	echo "orca CLI not found. Run: ORCA_BIN=/path/to/orca $0" >&2
	exit 1
fi

WRAPPER="$HERE/host.sh"
cat > "$WRAPPER" <<WRAPPER_EOF
#!/usr/bin/env bash
# Generated by install.sh. Machine specific, not committed.
export GOFISH_ORCA_BIN="$ORCA_BIN"
exec "$NODE_BIN" "$HERE/gofish-orca-host.mjs"
WRAPPER_EOF
chmod +x "$WRAPPER"

read -r -d '' MANIFEST <<MANIFEST_EOF || true
{
  "name": "$HOST_NAME",
  "description": "GoFish bridge to the Orca CLI",
  "path": "$WRAPPER",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXTENSION_ID/"]
}
MANIFEST_EOF

SUPPORT="$HOME/Library/Application Support"
TARGETS=(
	"$SUPPORT/Google/Chrome"
	"$SUPPORT/Google/Chrome Beta"
	"$SUPPORT/Google/Chrome Canary"
	"$SUPPORT/Chromium"
	"$SUPPORT/BraveSoftware/Brave-Browser"
	"$SUPPORT/BraveSoftware/Brave-Browser-Beta"
)

installed=0
for profile in "${TARGETS[@]}"; do
	[ -d "$profile" ] || continue
	mkdir -p "$profile/NativeMessagingHosts"
	printf '%s\n' "$MANIFEST" > "$profile/NativeMessagingHosts/$HOST_NAME.json"
	echo "installed: $profile/NativeMessagingHosts/$HOST_NAME.json"
	installed=$((installed + 1))
done

if [ "$installed" -eq 0 ]; then
	echo "No Chrome, Chromium or Brave profile directory found." >&2
	exit 1
fi

echo
echo "node: $NODE_BIN"
echo "orca: $ORCA_BIN"
echo "extension id: $EXTENSION_ID"
echo
echo "Restart the browser, then reload GoFish on the extensions page."
